
import React, { useState, useEffect } from 'react';
import { Concept, ScheduleItem } from '../types';
import { generateStudySchedule } from '../services/aiService';

interface StudyPlannerProps {
  subject: string;
  concepts: Concept[];
}

const StudyPlanner: React.FC<StudyPlannerProps> = ({ subject, concepts }) => {
  const [schedule, setSchedule] = useState<ScheduleItem[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const fetch = async () => {
      setLoading(true);
      try {
        const data = await generateStudySchedule(subject, concepts);
        setSchedule(data);
      } catch (e) {
        console.error(e);
      } finally {
        setLoading(false);
      }
    };
    if (concepts.length > 0) fetch();
  }, [subject, concepts]);

  if (loading) return <div className="p-12 animate-pulse">Planning your week...</div>;

  return (
    <div className="p-12 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-12">
        <div>
          <h3 className="text-2xl font-black text-slate-900">Study Itinerary</h3>
          <p className="text-sm text-slate-500">Optimized schedule generated by Gemini for <b>{subject}</b>.</p>
        </div>
        <div className="p-4 bg-indigo-50 text-indigo-600 rounded-2xl font-black text-xl">
          <i className="fas fa-calendar-day"></i>
        </div>
      </div>

      <div className="relative space-y-8 before:absolute before:left-[19px] before:top-4 before:bottom-4 before:w-0.5 before:bg-slate-100">
        {schedule.map((item, idx) => (
          <div key={item.id} className="relative pl-12">
            <div className="absolute left-0 top-1 w-10 h-10 rounded-full bg-white border-2 border-slate-100 flex items-center justify-center z-10">
              <span className="text-[10px] font-black text-slate-400">{idx + 1}</span>
            </div>
            <div className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm hover:shadow-lg transition-all border-l-4 border-l-indigo-500">
              <div className="flex justify-between items-start mb-2">
                <h4 className="font-bold text-slate-800">{item.title}</h4>
                <span className="px-2 py-1 bg-slate-50 text-[10px] font-black uppercase text-slate-400 rounded">{item.durationMinutes}m</span>
              </div>
              <p className="text-xs text-slate-500 leading-relaxed">{item.focus}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default StudyPlanner;
